#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

PUBLIC_CONFIG="public-config.toml"
PRIVATE_CONFIG="config.toml"

# Copy the public config into the private one: public-config.toml holds the
# shared "default settings", config.toml (gitignored) holds ALL settings and
# wins on conflicts. The result is a complete config.toml that Docker Compose
# mounts as /app/config.toml. Secrets are never written — api_key is a
# "$ENV_VAR" reference resolved from .env at runtime.
transfer_config() {
  python3 - "$PUBLIC_CONFIG" "$PRIVATE_CONFIG" <<'PY'
import sys
import tomllib

public_path, private_path = sys.argv[1:]


def load(path):
    try:
        with open(path, "rb") as f:
            return tomllib.load(f)
    except FileNotFoundError:
        return {}


def merge(base, over):
    out = dict(base)
    for key, value in over.items():
        if key in out and isinstance(out[key], dict) and isinstance(value, dict):
            out[key] = merge(out[key], value)
        else:
            out[key] = value
    return out


def toml_string(value):
    if "\n" in value:
        escaped = value.replace("\\", "\\\\").replace('"""', '\\"\\"\\"')
        return '"""' + escaped + '"""'
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return '"' + escaped + '"'


def fmt(value):
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        return repr(value)
    if isinstance(value, str):
        return toml_string(value)
    raise TypeError(f"unsupported TOML value: {value!r}")


def emit(f, table, prefix=""):
    scalars = {k: v for k, v in table.items() if not isinstance(v, dict)}
    tables = {k: v for k, v in table.items() if isinstance(v, dict)}
    lines = [f"{k} = {fmt(v)}" for k, v in scalars.items()]
    if lines:
        if prefix:
            f.write(f"[{prefix}]\n")
        f.write("\n".join(lines) + "\n\n")
    for key, value in tables.items():
        emit(f, value, f"{prefix}.{key}" if prefix else key)


result = merge(load(public_path), load(private_path))
with open(private_path, "w", encoding="utf-8") as f:
    f.write("# Generated by scripts/build.sh: merged from public-config.toml (defaults)\n"
            "# with config.toml (private) winning. config.toml is gitignored — never\n"
            "# commit it. Secrets only via .env references.\n\n")
    emit(f, result)
PY
}

transfer_config
docker compose build "$@"